modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/LGatodu47/ScreenshotViewer/issues"

[[mods]]
modId="screenshot_viewer"
version="${file.jarVersion}"
displayName="Screenshot Viewer"
logoFile="icon.png"
authors="LGatodu47"
displayTest="IGNORE_ALL_VERSION"
description="A mod that allows you to see and manage your screenshots in game!"

[[dependencies.screenshot_viewer]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="CLIENT"

[[dependencies.screenshot_viewer]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.19.3)"
ordering="NONE"
side="CLIENT"
